# Generated by Django 3.2 on 2023-10-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
