# Generated by Django 3.2 on 2023-11-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_alter_game_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended_by_forfeit',
            field=models.BooleanField(null=True),
        ),
    ]
