# Generated by Django 3.2 on 2023-11-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0005_confirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
